[package]
name = "ftth-dhcp"
version = "0.1.0"
edition = "2024"

[dependencies]
dhcproto = "0.13"
ftth-rtnl = "0.1.0"
ipnet = "2"
log = "0.4.28"
socket2 = { version = "0.6.0", features = ["all"] }

[dev-dependencies]
rand = "0.9"